//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rico.S14.MaoYanMovie.CinemaImage {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CinemaImage.FilmPhotoSoap")]
    public interface FilmPhotoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilmPosterUpload", ReplyAction="*")]
        Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadResponse FilmPosterUpload(Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilmPosterUpload", ReplyAction="*")]
        System.Threading.Tasks.Task<Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadResponse> FilmPosterUploadAsync(Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilmScreenUpload", ReplyAction="*")]
        Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadResponse FilmScreenUpload(Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FilmScreenUpload", ReplyAction="*")]
        System.Threading.Tasks.Task<Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadResponse> FilmScreenUploadAsync(Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilmPosterUploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilmPosterUpload", Namespace="http://tempuri.org/", Order=0)]
        public Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadRequestBody Body;
        
        public FilmPosterUploadRequest() {
        }
        
        public FilmPosterUploadRequest(Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilmPosterUploadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string keyt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] datas;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid filmId;
        
        public FilmPosterUploadRequestBody() {
        }
        
        public FilmPosterUploadRequestBody(string keyt, byte[] datas, System.Guid filmId) {
            this.keyt = keyt;
            this.datas = datas;
            this.filmId = filmId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilmPosterUploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilmPosterUploadResponse", Namespace="http://tempuri.org/", Order=0)]
        public Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadResponseBody Body;
        
        public FilmPosterUploadResponse() {
        }
        
        public FilmPosterUploadResponse(Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilmPosterUploadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool FilmPosterUploadResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string imagePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        public FilmPosterUploadResponseBody() {
        }
        
        public FilmPosterUploadResponseBody(bool FilmPosterUploadResult, string imagePath, string message) {
            this.FilmPosterUploadResult = FilmPosterUploadResult;
            this.imagePath = imagePath;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilmScreenUploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilmScreenUpload", Namespace="http://tempuri.org/", Order=0)]
        public Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadRequestBody Body;
        
        public FilmScreenUploadRequest() {
        }
        
        public FilmScreenUploadRequest(Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilmScreenUploadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string keyt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] datas;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid filmId;
        
        public FilmScreenUploadRequestBody() {
        }
        
        public FilmScreenUploadRequestBody(string keyt, byte[] datas, System.Guid filmId) {
            this.keyt = keyt;
            this.datas = datas;
            this.filmId = filmId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FilmScreenUploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FilmScreenUploadResponse", Namespace="http://tempuri.org/", Order=0)]
        public Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadResponseBody Body;
        
        public FilmScreenUploadResponse() {
        }
        
        public FilmScreenUploadResponse(Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FilmScreenUploadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool FilmScreenUploadResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string imagePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        public FilmScreenUploadResponseBody() {
        }
        
        public FilmScreenUploadResponseBody(bool FilmScreenUploadResult, string imagePath, string message) {
            this.FilmScreenUploadResult = FilmScreenUploadResult;
            this.imagePath = imagePath;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FilmPhotoSoapChannel : Rico.S14.MaoYanMovie.CinemaImage.FilmPhotoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilmPhotoSoapClient : System.ServiceModel.ClientBase<Rico.S14.MaoYanMovie.CinemaImage.FilmPhotoSoap>, Rico.S14.MaoYanMovie.CinemaImage.FilmPhotoSoap {
        
        public FilmPhotoSoapClient() {
        }
        
        public FilmPhotoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilmPhotoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilmPhotoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilmPhotoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadResponse Rico.S14.MaoYanMovie.CinemaImage.FilmPhotoSoap.FilmPosterUpload(Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadRequest request) {
            return base.Channel.FilmPosterUpload(request);
        }
        
        public bool FilmPosterUpload(string keyt, byte[] datas, System.Guid filmId, out string imagePath, out string message) {
            Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadRequest inValue = new Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadRequest();
            inValue.Body = new Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadRequestBody();
            inValue.Body.keyt = keyt;
            inValue.Body.datas = datas;
            inValue.Body.filmId = filmId;
            Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadResponse retVal = ((Rico.S14.MaoYanMovie.CinemaImage.FilmPhotoSoap)(this)).FilmPosterUpload(inValue);
            imagePath = retVal.Body.imagePath;
            message = retVal.Body.message;
            return retVal.Body.FilmPosterUploadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadResponse> Rico.S14.MaoYanMovie.CinemaImage.FilmPhotoSoap.FilmPosterUploadAsync(Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadRequest request) {
            return base.Channel.FilmPosterUploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadResponse> FilmPosterUploadAsync(string keyt, byte[] datas, System.Guid filmId) {
            Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadRequest inValue = new Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadRequest();
            inValue.Body = new Rico.S14.MaoYanMovie.CinemaImage.FilmPosterUploadRequestBody();
            inValue.Body.keyt = keyt;
            inValue.Body.datas = datas;
            inValue.Body.filmId = filmId;
            return ((Rico.S14.MaoYanMovie.CinemaImage.FilmPhotoSoap)(this)).FilmPosterUploadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadResponse Rico.S14.MaoYanMovie.CinemaImage.FilmPhotoSoap.FilmScreenUpload(Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadRequest request) {
            return base.Channel.FilmScreenUpload(request);
        }
        
        public bool FilmScreenUpload(string keyt, byte[] datas, System.Guid filmId, out string imagePath, out string message) {
            Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadRequest inValue = new Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadRequest();
            inValue.Body = new Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadRequestBody();
            inValue.Body.keyt = keyt;
            inValue.Body.datas = datas;
            inValue.Body.filmId = filmId;
            Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadResponse retVal = ((Rico.S14.MaoYanMovie.CinemaImage.FilmPhotoSoap)(this)).FilmScreenUpload(inValue);
            imagePath = retVal.Body.imagePath;
            message = retVal.Body.message;
            return retVal.Body.FilmScreenUploadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadResponse> Rico.S14.MaoYanMovie.CinemaImage.FilmPhotoSoap.FilmScreenUploadAsync(Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadRequest request) {
            return base.Channel.FilmScreenUploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadResponse> FilmScreenUploadAsync(string keyt, byte[] datas, System.Guid filmId) {
            Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadRequest inValue = new Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadRequest();
            inValue.Body = new Rico.S14.MaoYanMovie.CinemaImage.FilmScreenUploadRequestBody();
            inValue.Body.keyt = keyt;
            inValue.Body.datas = datas;
            inValue.Body.filmId = filmId;
            return ((Rico.S14.MaoYanMovie.CinemaImage.FilmPhotoSoap)(this)).FilmScreenUploadAsync(inValue);
        }
    }
}
