<Query Kind="Expression">
  <Connection>
    <ID>8f35cbb5-7d32-4780-9466-d2ea7df6801a</ID>
    <Persist>true</Persist>
    <Server>192.168.1.218\mighost</Server>
    <SqlSecurity>true</SqlSecurity>
    <UserName>sa</UserName>
    <Password>AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAABoybHsSXFUuz8AXaKmCqgAAAAAACAAAAAAAQZgAAAAEAACAAAAAY1L2xKXxTEwafKLsJIgRLp3lTtHAGIZJKfzP+Cm/fnQAAAAAOgAAAAAIAACAAAABFxQ3QIGCW+GW9ZwBRjYCQKjMVsx68ZWf41kU/8x/YExAAAADltx+Q8L+jR8smKtSA1KvTQAAAAAkFR+NNcSvAp0ax3jBbCKBrfQNaSCf3lR+Faqk/qDBA6Gqf9Zq2yxWWG/Dt5DcbvpxE6mq07V0vP7xoxwZR4r8=</Password>
    <Database>CinemaWdTest</Database>
    <ShowServer>true</ShowServer>
  </Connection>
  <Output>DataGrids</Output>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Antlr3.Runtime.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Cinema.AppWeb.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Cinema.Audit.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Cinema.Caches.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Cinema.Core.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Cinema.SmsService.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Cinema.Util.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Cinema.YueKe.Service.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Domain.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Domain.Identity.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Storage.EntityFramework.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Storage.EntityFramework.Identity.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Thirdparty.Alipay.AppPay.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Thirdparty.Wechat.AppPay.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Utility.Configuration.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Utility.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Utility.Exceptional.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Utility.Http.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Utility.Logger.Ado.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Utility.Serialization.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Web.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Web.Identity.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\EntityFramework.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\EntityFramework.SqlServer.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.AspNet.Identity.Core.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.AspNet.Identity.Owin.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Owin.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Owin.Host.SystemWeb.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Owin.Security.Cookies.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Owin.Security.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Owin.Security.OAuth.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Practices.ServiceLocation.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Practices.Unity.Configuration.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Practices.Unity.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Practices.Unity.Interception.Configuration.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Practices.Unity.Interception.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Practices.Unity.RegistrationByConvention.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Web.Infrastructure.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Newtonsoft.Json.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Owin.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\StackExchange.Redis.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Net.Http.Extensions.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Net.Http.Formatting.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Net.Http.Primitives.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Helpers.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Http.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Http.Owin.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Mvc.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Optimization.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Razor.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Webpages.Deployment.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Webpages.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Webpages.Razor.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\WebGrease.dll</Reference>
  <Namespace>Cinema.Core.Domain.Models.Values</Namespace>
</Query>

Orders.OrderByDescending(a => a.CreateTime).Take(10).ToList().Select(a => new
{
	创建时间 = a.CreateTime.ToString("yyyy-MM-dd HH:mm:ss"),
	状态=((OrderStatus)a.Status).ReadEnumDescription(),
	支付方式=((PayType)a.PayType).ReadEnumDescription(),
	a.TicketCount,
	a.OldTotal,
	a.Total,
	a.CardTotal,
	a.ThirdPay,
	a.Mobile,
	
	a.PayCardNum,
	a.ConfirmationId,
	a.MerchantOrderId,
	a.ThirdpartyOrderId,
	a.LimitDiscountId,
	a.RedPacketId,
	a.GoodsTotal,
	a.TotalGoodsFee,
	a.PickUpCode,
	a.HoldId,
	a.Id,
	a.LockOrderId,
	a.OutLockId,
	a.BookingId,
	a.OrderCode,
	a.ExpireTime,
})