
/****** Object:  Table [dbo].[T_PRODUCT]    Script Date: 10/22/2010 15:16:43 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[T_PRODUCT]') AND type in (N'U'))
DROP TABLE [dbo].[T_PRODUCT]
GO

CREATE TABLE [dbo].[T_PRODUCT](
	[ID]				[VARCHAR](50) NOT NULL,
	[NAME]				[NVARCHAR] NOT NULL,
	[PRICE]				[float] NOT NULL,
	[TOTAL_PRICE]		[FLOAT] NOT NULL,
	[DESC]				[NVARCHAR]  NULL,

	[CREATED_BY]		[VARCHAR](50) NULL,
	[CREATED_ON]		[DATETIME] NULL,
	[LAST_UPDATED_BY]	[VARCHAR](50) NULL,
	[LAST_UPDATED_ON]	[DATETIME] NULL,
	[VERSION_NO]		[TIMESTAMP] NULL,
	[TRANSACTION_ID]	[VARCHAR](50) NULL,
 CONSTRAINT [PK_T_PRODUCT] PRIMARY KEY CLUSTERED( [ID] ASC)ON [PRIMARY])

GO