<Query Kind="SQL">
  <Connection>
    <ID>edb569e0-1029-4670-bd56-f4981986d255</ID>
    <Persist>true</Persist>
    <Server>101.132.69.71</Server>
    <SqlSecurity>true</SqlSecurity>
    <UserName>sa</UserName>
    <Password>AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAABoybHsSXFUuz8AXaKmCqgAAAAAACAAAAAAAQZgAAAAEAACAAAADlMDTg8rh8stUlZgjvxKWfJkLaoJu5GrJnhua9EICUhQAAAAAOgAAAAAIAACAAAAB7x+0HnQ6b0YgF1diupbyFoqj8o5uo5sGeSJrsiKJKHBAAAABM8IUq4NDIt9vX4B4yLwcyQAAAAJFB1V+gp2sgHISifMpmzqEsGAOnWOnhx7O3RcsGhbmZYn41eVGBCO7ch97kncwveJgTFqk5lA+bm4awvliGAl0=</Password>
    <Database>CinemaWd</Database>
    <ShowServer>true</ShowServer>
  </Connection>
  <Output>DataGrids</Output>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Antlr3.Runtime.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Cinema.AppWeb.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Cinema.Audit.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Cinema.Caches.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Cinema.Core.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Cinema.SmsService.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Cinema.Util.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Cinema.YueKe.Service.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Domain.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Domain.Identity.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Storage.EntityFramework.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Storage.EntityFramework.Identity.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Thirdparty.Alipay.AppPay.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Thirdparty.Wechat.AppPay.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Utility.Configuration.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Utility.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Utility.Exceptional.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Utility.Http.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Utility.Logger.Ado.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Utility.Serialization.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Web.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\DRapid.Web.Identity.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\EntityFramework.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\EntityFramework.SqlServer.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.AspNet.Identity.Core.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.AspNet.Identity.Owin.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Owin.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Owin.Host.SystemWeb.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Owin.Security.Cookies.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Owin.Security.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Owin.Security.OAuth.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Practices.ServiceLocation.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Practices.Unity.Configuration.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Practices.Unity.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Practices.Unity.Interception.Configuration.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Practices.Unity.Interception.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Practices.Unity.RegistrationByConvention.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Microsoft.Web.Infrastructure.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Newtonsoft.Json.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\Owin.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\StackExchange.Redis.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Net.Http.Extensions.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Net.Http.Formatting.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Net.Http.Primitives.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Helpers.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Http.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Http.Owin.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Mvc.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Optimization.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Razor.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Webpages.Deployment.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Webpages.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\System.Web.Webpages.Razor.dll</Reference>
  <Reference>D:\00-baitu-tfs\TFS-2013\Cinema\master\src\Cinema.AppWeb\bin\WebGrease.dll</Reference>
  <Namespace>Cinema.Core.Domain.Models.Values</Namespace>
</Query>


--结论：2018-11-10 13867069902 在11月10号这个用户124元买了4张票，先用支付宝支付后用户会员卡支付
select PayType,* from [order] where id='d9138490-295b-4af7-b8f8-7ffc041a21bc'
update [order] set PayType=1  where id='d9138490-295b-4af7-b8f8-7ffc041a21bc'